name: Testes e Cobertura (CI)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Testar em Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 20.x, 22.x]

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: 📦 Instalar dependências
        run: npm ci

      - name: 🧪 Rodar testes com Mocha
        run: npm test
